[build]
  base = "project"
  publish = "project/dist"
  command = "npm install && npx playwright install chromium --with-deps && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/screenshots/*"
  to = "/.netlify/functions/server/screenshots/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "project/netlify/functions"
  node_bundler = "esbuild"